### ISSUE TITLE
Plugin broken on pytest release 4.1.0

### ISSUE THREAD

**Issue by theunkn0wn1** [pytest-dev/pytest-asyncio#107]
Pytest-asyncio plugin causes pytest to crash during loading, as a result of using a now removed API.

appears to be caused by https://github.com/pytest-dev/pytest/pull/4564/ which is included in Pytest version  4.1.0

Exception stacktrace:
```
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/project/bin/pytest", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/virtualenvs/project/lib/python3.7/site-packages/_pytest/config/__init__.py", line 61, in main
    config = _prepareconfig(args, plugins)
  File "/root/.local/share/virtualenvs/project/lib/python3.7/site-packages/_pytest/config/__init__.py", line 196, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "/root/.local/share/virtualenvs/project/lib/python3.7/site-packages/pluggy/hooks.py", line 284, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/root/.local/share/virtualenvs/project/lib/python3.7/site-packages/pluggy/manager.py", line 67, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/root/.local/share/virtualenvs/project/lib/python3.7/site-packages/pluggy/manager.py", line 61, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/root/.local/share/virtualenvs/project/lib/python3.7/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/root/.local/share/virtualenvs/project/lib/python3.7/site-packages/_pytest/helpconfig.py", line 93, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/root/.local/share/virtualenvs/project/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/root/.local/share/virtualenvs/project/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/root/.local/share/virtualenvs/project/lib/python3.7/site-packages/_pytest/config/__init__.py", line 652, in pytest_cmdline_parse
    self.parse(args)
  File "/root/.local/share/virtualenvs/project/lib/python3.7/site-packages/_pytest/config/__init__.py", line 838, in parse
    self._preparse(args, addopts=addopts)
  File "/root/.local/share/virtualenvs/project/lib/python3.7/site-packages/_pytest/config/__init__.py", line 784, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/root/.local/share/virtualenvs/project/lib/python3.7/site-packages/pluggy/manager.py", line 267, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/root/.local/share/virtualenvs/project/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/root/.local/share/virtualenvs/project/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/root/.local/share/virtualenvs/project/lib/python3.7/site-packages/_pytest/assertion/rewrite.py", line 308, in load_module
    six.exec_(co, mod.__dict__)
  File "/root/.local/share/virtualenvs/project/lib/python3.7/site-packages/pytest_asyncio/plugin.py", line 8, in <module>
    from _pytest.python import transfer_markers
ImportError: cannot import name 'transfer_markers' from '_pytest.python' (/root/.local/share/virtualenvs/project/lib/python3.7/site-packages/_pytest/python.py)
```

**Comment by theunkn0wn1** [comment]
Duplicate of #104

I didn't look hard enough. SorrY!
