### ISSUE TITLE
"Task exception was never retrieved" when using pytest.raises

### ISSUE THREAD

**Issue by matejcik** [pytest-dev/pytest-asyncio#116]
didn't check master, this happens with released pytest-asyncio 0.10.0

```python
import pytest

@pytest.mark.asyncio
async def test_simple():
    with pytest.raises(Exception):
        pass
```

pytest will print normal results (failed test), and _in addition_ after the normal output ends, the following noisy stacktrace is printed:
```
Task exception was never retrieved
future: <Task finished coro=<test_simple() done, defined at /home/matejcik/projekty/prace/microwallet/testtest.py:3> exception=DID NOT RAISE <class 'Exception'>>
Traceback (most recent call last):
  File "/home/matejcik/.virtualenvs/trezor/lib/python3.6/site-packages/_pytest/runner.py", line 226, in from_call
    result = func()
  File "/home/matejcik/.virtualenvs/trezor/lib/python3.6/site-packages/_pytest/runner.py", line 198, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File "/home/matejcik/.virtualenvs/trezor/lib/python3.6/site-packages/pluggy/hooks.py", line 284, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/matejcik/.virtualenvs/trezor/lib/python3.6/site-packages/pluggy/manager.py", line 68, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/matejcik/.virtualenvs/trezor/lib/python3.6/site-packages/pluggy/manager.py", line 62, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/matejcik/.virtualenvs/trezor/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/matejcik/.virtualenvs/trezor/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/matejcik/.virtualenvs/trezor/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/matejcik/.virtualenvs/trezor/lib/python3.6/site-packages/_pytest/runner.py", line 123, in pytest_runtest_call
    item.runtest()
  File "/home/matejcik/.virtualenvs/trezor/lib/python3.6/site-packages/_pytest/python.py", line 1357, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/home/matejcik/.virtualenvs/trezor/lib/python3.6/site-packages/pluggy/hooks.py", line 284, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/matejcik/.virtualenvs/trezor/lib/python3.6/site-packages/pluggy/manager.py", line 68, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/matejcik/.virtualenvs/trezor/lib/python3.6/site-packages/pluggy/manager.py", line 62, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/matejcik/.virtualenvs/trezor/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/matejcik/.virtualenvs/trezor/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/matejcik/.virtualenvs/trezor/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/matejcik/.virtualenvs/trezor/lib/python3.6/site-packages/pytest_asyncio/plugin.py", line 158, in pytest_pyfunc_call
    pyfuncitem.obj(**testargs), loop=event_loop))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 460, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 427, in run_forever
    self._run_once()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1440, in _run_once
    handle._run()
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/home/matejcik/projekty/prace/microwallet/testtest.py", line 6, in test_simple
    pass
  File "/home/matejcik/.virtualenvs/trezor/lib/python3.6/site-packages/_pytest/python_api.py", line 721, in __exit__
    fail(self.message)
  File "/home/matejcik/.virtualenvs/trezor/lib/python3.6/site-packages/_pytest/outcomes.py", line 113, in fail
    raise Failed(msg=msg, pytrace=pytrace)
Failed: DID NOT RAISE <class 'Exception'>
```

**Comment by blueyed** [comment]
Fixed by 86cd9a6 (just merged).
Thanks for the report!
