### ISSUE TITLE
Expose default value for mode by hook

### ISSUE THREAD

**Issue by tkukushkin** [pytest-dev/pytest-asyncio#263]
We have hundreds of microservices that use our plugin to avoid writing an extra boilerplate in each service's repository. We want to set `auto` mode to all services by this plugin. If you expose the default value as hook, our plugin will be able to change it for all services. 

Example from documentation: https://docs.pytest.org/en/latest/how-to/writing_hook_functions.html#using-hooks-in-pytest-addoption

**Comment by asvetlov** [comment]
Interesting idea.
How should API look in your mind?

**Comment by tkukushkin** [comment]
Something like this:
```python
# contest.py
def pytest_asyncio_default_mode() -> str:
    return "auto"
```

**Comment by asvetlov** [comment]
How is it different from already supported approach:
```
def pytest_configure(config):
    config.addinivalue_line("asyncio_mode", "auto")
```
???

**Comment by tkukushkin** [comment]
As I understand, `addinivalue_line` supports only options with multiple values, like `filterwarnings`.

With your code pytest crashes with such traceback:

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File ".../lib/python3.9/site-packages/_pytest/main.py", line 265, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File ".../lib/python3.9/site-packages/_pytest/config/__init__.py", line 982, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File ".../lib/python3.9/site-packages/pluggy/_hooks.py", line 277, in call_historic
INTERNALERROR>     res = self._hookexec(self.name, self.get_hookimpls(), kwargs, False)
INTERNALERROR>   File ".../lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File ".../lib/python3.9/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File ".../lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File ".../lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Users/tkukushkin/Projects/python.cian-test-utils/src/cian_test_utils/pytest_plugin/__init__.py", line 15, in pytest_configure
INTERNALERROR>     config.addinivalue_line("asyncio_mode", "auto")
INTERNALERROR>   File ".../lib/python3.9/site-packages/_pytest/config/__init__.py", line 1348, in addinivalue_line
INTERNALERROR>     assert isinstance(x, list)
INTERNALERROR> AssertionError
```

**Comment by asvetlov** [comment]
Aha, I see.
Another alternative could be `config.option.asyncio_mode = 'auto'`

**Comment by tkukushkin** [comment]
Wow, that really works, didn't know about `config.option`. Thanks!
