### ISSUE TITLE
pluggy.manager.PluginValidationError: Plugin 'asyncio' for hook 'pytest_addoption'

### ISSUE THREAD

**Issue by skelutten** [pytest-dev/pytest-asyncio#294]
Hi

I wantd to try out pytest-asyncio for some tests running in a Docker container.
Python 3.8.10
pluggy             0.13.0  
pytest             4.6.9   
pytest-asyncio     0.18.1

When I launch pytest it immediately gives an error:
```
Traceback (most recent call last):
  File "/usr/bin/pytest-3", line 11, in <module>
    load_entry_point('pytest==4.6.9', 'console_scripts', 'pytest')()
  File "/usr/lib/python3/dist-packages/_pytest/config/__init__.py", line 63, in main
    config = _prepareconfig(args, plugins)
  File "/usr/lib/python3/dist-packages/_pytest/config/__init__.py", line 206, in _prepareconfig
    return pluginmanager.hook.pytest_cmdline_parse(
  File "/usr/lib/python3/dist-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/lib/python3/dist-packages/pluggy/manager.py", line 92, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/lib/python3/dist-packages/pluggy/manager.py", line 83, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/usr/lib/python3/dist-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/usr/lib/python3/dist-packages/_pytest/helpconfig.py", line 94, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/usr/lib/python3/dist-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/lib/python3/dist-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/lib/python3/dist-packages/_pytest/config/__init__.py", line 739, in pytest_cmdline_parse
    self.parse(args)
  File "/usr/lib/python3/dist-packages/_pytest/config/__init__.py", line 947, in parse
    self._preparse(args, addopts=addopts)
  File "/usr/lib/python3/dist-packages/_pytest/config/__init__.py", line 893, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/usr/lib/python3/dist-packages/pluggy/manager.py", line 298, in load_setuptools_entrypoints
    self.register(plugin, name=ep.name)
  File "/usr/lib/python3/dist-packages/_pytest/config/__init__.py", line 321, in register
    ret = super(PytestPluginManager, self).register(plugin, name)
  File "/usr/lib/python3/dist-packages/pluggy/manager.py", line 125, in register
    self._verify_hook(hook, hookimpl)
  File "/usr/lib/python3/dist-packages/pluggy/manager.py", line 250, in _verify_hook
    raise PluginValidationError(
pluggy.manager.PluginValidationError: Plugin 'asyncio' for hook 'pytest_addoption'
hookimpl definition: pytest_addoption(parser: Any, pluginmanager: Any) -> None
Argument(s) {'pluginmanager'} are declared in the hookimpl but can not be found in the hookspec
```
Are the versions listed above not compatible?

Cheers,

Daniel

**Comment by asvetlov** [comment]
`pytest-asyncio` requires `pytest>=6.1.0`: https://github.com/pytest-dev/pytest-asyncio/blob/master/setup.cfg#L38
I have no ide how did you install pytest==4.6.9 with pytest-asyncio==0.18.1

**Comment by asvetlov** [comment]
`from_parent` was added by pytest 6.x line.
6.1.0 definitely has `pluginmanager` argument for the hook: https://github.com/pytest-dev/pytest/blob/6.1.x/src/_pytest/hookspec.py#L80
Also, pytest-asyncio CI has the explicit 'minimal' configuration that checks its own tests passing with minimal supported Python (3.7) and pytest (6.1.0).

Please double-check your requirements.
