### ISSUE TITLE
Argument(s) {'pluginmanager'} are declared in the hookimpl but can not be found in the hookspec

### ISSUE THREAD

**Issue by dsouzan** [pytest-dev/pytest-asyncio#299]
Context : I am trying to fix this warning - The 'asyncio_mode' default value will change to 'strict' in future, please explicitly use 'asyncio_mode=strict' or 'asyncio_mode=auto' in pytest configuration file.

Repro Steps:
1.pip3 install pytest-asyncio
2. pytest-3 test/test_requirements.py --asyncio-mode=strict

<error>

:~/cve-bin-tool$ pytest-3 test/test_requirements.py --asyncio-mode=strict
Traceback (most recent call last):
  File "/usr/bin/pytest-3", line 11, in <module>
    load_entry_point('pytest==4.6.9', 'console_scripts', 'pytest')()
  File "/usr/lib/python3/dist-packages/_pytest/config/__init__.py", line 63, in main
    config = _prepareconfig(args, plugins)
  File "/usr/lib/python3/dist-packages/_pytest/config/__init__.py", line 206, in _prepareconfig
    return pluginmanager.hook.pytest_cmdline_parse(
  File "/usr/lib/python3/dist-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/lib/python3/dist-packages/pluggy/manager.py", line 92, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/lib/python3/dist-packages/pluggy/manager.py", line 83, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/usr/lib/python3/dist-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/usr/lib/python3/dist-packages/_pytest/helpconfig.py", line 94, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/usr/lib/python3/dist-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/lib/python3/dist-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/lib/python3/dist-packages/_pytest/config/__init__.py", line 739, in pytest_cmdline_parse
    self.parse(args)
  File "/usr/lib/python3/dist-packages/_pytest/config/__init__.py", line 947, in parse
    self._preparse(args, addopts=addopts)
  File "/usr/lib/python3/dist-packages/_pytest/config/__init__.py", line 893, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/usr/lib/python3/dist-packages/pluggy/manager.py", line 298, in load_setuptools_entrypoints
    self.register(plugin, name=ep.name)
  File "/usr/lib/python3/dist-packages/_pytest/config/__init__.py", line 321, in register
    ret = super(PytestPluginManager, self).register(plugin, name)
  File "/usr/lib/python3/dist-packages/pluggy/manager.py", line 125, in register
    self._verify_hook(hook, hookimpl)
  File "/usr/lib/python3/dist-packages/pluggy/manager.py", line 250, in _verify_hook
    raise PluginValidationError(
pluggy.manager.PluginValidationError: Plugin 'asyncio' for hook 'pytest_addoption'
hookimpl definition: pytest_addoption(parser: Any, pluginmanager: Any) -> None
Argument(s) {'pluginmanager'} are declared in the hookimpl but can not be found in the hookspec

**Comment by asvetlov** [comment]
The plugin requires pytest 5.1+.
I'm curious: How was you able to install the latest pytest-asyncio with pytest 4.x?
Do you use outdated pip?

**Comment by dsouzan** [comment]
I just did this.

pip3 install pytest-asyncio

The pip3 version : pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)

**Comment by dsouzan** [comment]
$ pip install --upgrade pytest
Requirement already up-to-date: pytest in /home/ndsouza/.local/lib/python3.8/site-packages (7.0.1)
Requirement already satisfied, skipping upgrade: attrs>=19.2.0 in /usr/lib/python3/dist-packages (from pytest) (19.3.0)
Requirement already satisfied, skipping upgrade: iniconfig in /home/ndsouza/.local/lib/python3.8/site-packages (from pytest) (1.1.1)
Requirement already satisfied, skipping upgrade: pluggy<2.0,>=0.12 in /usr/lib/python3/dist-packages (from pytest) (0.13.0)
Requirement already satisfied, skipping upgrade: tomli>=1.0.0 in /home/ndsouza/.local/lib/python3.8/site-packages (from pytest) (2.0.1)
Requirement already satisfied, skipping upgrade: py>=1.8.2 in /home/ndsouza/.local/lib/python3.8/site-packages (from pytest) (1.11.0)
Requirement already satisfied, skipping upgrade: packaging in /usr/lib/python3/dist-packages (from pytest) (20.3)

I get the above error with pytest-3.

But with pytest I get :

~/cve-bin-tool$ pytest test/test_requirements.py --asyncio-mode=strict
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --asyncio-mode=strict
  inifile: None
  rootdir: /home/ndsouza/cve-bin-tool

**Comment by seifertm** [comment]
@dsouzan I'm pretty confident this is an issue with your environment. As Andrew mentioned, pytest-asyncio requires at least pytest 6.1.

Can you upgrade to a recent version of pytest and report back if that fixes the issue?

**Comment by dsouzan** [comment]
@seifertm, you are correct, there is a problem with my environment. i will need to chase it down. Perhaps I am not using pytest-3 correctly.

I have a workaround _

ndsouza@ndsouza-ws:~/cve-bin-tool$ python3 -m pytest test/test_requirements.py --asyncio-mode=strict
============================================================================================ test session starts =============================================================================================
platform linux -- Python 3.8.10, pytest-7.0.1, pluggy-0.13.0
rootdir: /home/ndsouza/cve-bin-tool
plugins: asyncio-0.18.1
asyncio: mode=strict
collected 2 items

**Comment by seifertm** [comment]
That output looks better :)
I'm closing this issue, but feel free to reach out if you have questions or if you experience any other issues.
