### ISSUE TITLE
pytest-asyncio hangs pytest

### ISSUE THREAD

**Issue by mborsetti** [pytest-dev/pytest-asyncio#343]
On Windows 11, `pytest` freezes if `pytest-asyncio` is present, and will stay frozen until I press Ctrl-C.

From the error trace, it appears that `assertion/rewrite.py` is trying to write a temporary file within the library directory (and, obviously, no privileges to do so) vs. the correct way of doing so in the temporary directory.

```
C:\Users\mike\Documents\python\git_repos\webchanges>pytest --version
Traceback (most recent call last):
  File "C:\Program Files\Python\Python310\lib\tempfile.py", line 256, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
PermissionError: [Errno 13] Permission denied: 'C:\\Program Files\\Python\\Python310\\lib\\site-packages\\pytest_asyncio\\__pycache__\\tmpfce13oq8'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python\Python310\Scripts\pytest.exe\__main__.py", line 7, in <module>
  File "C:\Program Files\Python\Python310\lib\site-packages\_pytest\config\__init__.py", line 187, in console_main
    code = main()
  File "C:\Program Files\Python\Python310\lib\site-packages\_pytest\config\__init__.py", line 145, in main
    config = _prepareconfig(args, plugins)
  File "C:\Program Files\Python\Python310\lib\site-packages\_pytest\config\__init__.py", line 324, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "C:\Program Files\Python\Python310\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "C:\Program Files\Python\Python310\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Program Files\Python\Python310\lib\site-packages\pluggy\_callers.py", line 55, in _multicall
    gen.send(outcome)
  File "C:\Program Files\Python\Python310\lib\site-packages\_pytest\helpconfig.py", line 102, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "C:\Program Files\Python\Python310\lib\site-packages\pluggy\_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "C:\Program Files\Python\Python310\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "C:\Program Files\Python\Python310\lib\site-packages\_pytest\config\__init__.py", line 1016, in pytest_cmdline_parse
    self.parse(args)
  File "C:\Program Files\Python\Python310\lib\site-packages\_pytest\config\__init__.py", line 1304, in parse
    self._preparse(args, addopts=addopts)
  File "C:\Program Files\Python\Python310\lib\site-packages\_pytest\config\__init__.py", line 1187, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "C:\Program Files\Python\Python310\lib\site-packages\pluggy\_manager.py", line 287, in load_setuptools_entrypoints
    plugin = ep.load()
  File "C:\Program Files\Python\Python310\lib\importlib\metadata\__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "C:\Program Files\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Program Files\Python\Python310\lib\site-packages\_pytest\assertion\rewrite.py", line 163, in exec_module
    _write_pyc(state, co, source_stat, pyc)
  File "C:\Program Files\Python\Python310\lib\site-packages\_pytest\assertion\rewrite.py", line 315, in _write_pyc
    with atomic_write(os.fspath(pyc), mode="wb", overwrite=True) as fp:
  File "C:\Program Files\Python\Python310\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "C:\Program Files\Python\Python310\lib\site-packages\atomicwrites\__init__.py", line 166, in _open
    with get_fileobject(**self._open_kwargs) as f:
  File "C:\Program Files\Python\Python310\lib\site-packages\atomicwrites\__init__.py", line 183, in get_fileobject
    descriptor, name = tempfile.mkstemp(suffix=suffix, prefix=prefix,
  File "C:\Program Files\Python\Python310\lib\tempfile.py", line 341, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "C:\Program Files\Python\Python310\lib\tempfile.py", line 256, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
KeyboardInterrupt
^C
```

Encountered in both Python 3.10 and 3.9, with and without a specified `pytest.ini` file.  Once `pytest-asyncio` is uninstalled, `pytest` resumes working.

```
pytest==7.1.2
pytest-asyncio==0.18.3
```

**Comment by mborsetti** [comment]
Transient issue.  A reinstall fixed it.
