### ISSUE TITLE
Using async testcases creates "empty" testcases in junit xml file using option --junitxml=xxx

### ISSUE THREAD

**Issue by mh7d** [pytest-dev/pytest-asyncio#369]
I have a testsuite containing several async testcases using @pytest.mark.asyncio.

I use the --junitxml=xxx option to generate a report which can be used in Azure DevOps for test reports. in some situations I get a warning in DevOps, that not all testcases can be displayed. When going into details, I found out, that in in the generated xml file, there are extra testcases having no name, each of them before one of the async test_cases. 

Example code:

```
import os
import xml.etree.ElementTree as et
import pytest

def test_junitxml_using_one_async_testcase(pytester: pytest.Pytester):
    pytester.makepyfile("""
    @pytest.mark.asyncio
    async def test_run2(self):
        assert True    
    """)

    pytester.makeconftest("")

    result = pytester.runpytest("--junitxml=junit.xml")
    root_node = et.parse(os.path.join(pytester.path, 'junit.xml')).getroot()
    test_cases = root_node.findall('.//*')

    assert result.assert_outcomes(passed=1)
    assert sum(x.tag == 'testcase' for x in test_cases) == 1
```

Some parser of the junit xml file seems to have problem with these  extra empty testcases.

**Comment by seifertm** [comment]
Thanks for the report! I believe the junit report generation did not get much attention in the past. As far as I know, there are no tests for this functionality at the moment.

I added `import os` to your example, so it runs with `pytest -p pytester`.

When I run your provided example, I get the following `junit.xml` output:
```
<?xml version="1.0" encoding="utf-8"?>
<testsuites>
  <testsuite name="pytest" errors="1" failures="0" skipped="0" tests="1" time="0.023" timestamp="2022-06-26T11:02:20.318861" hostname="msnote0">
    <testcase classname="pytest" name="internal" time="0.000">
      <error message="internal error">Traceback (most recent call last):
  File "/tmp/pa-test2/venv/lib/python3.9/site-packages/_pytest/main.py", line 268, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "/tmp/pa-test2/venv/lib/python3.9/site-packages/_pytest/main.py", line 321, in _main
    config.hook.pytest_collection(session=session)
  File "/tmp/pa-test2/venv/lib/python3.9/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/tmp/pa-test2/venv/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/tmp/pa-test2/venv/lib/python3.9/site-packages/pluggy/_manager.py", line 327, in traced_hookexec
    return outcome.get_result()
  File "/tmp/pa-test2/venv/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/tmp/pa-test2/venv/lib/python3.9/site-packages/pluggy/_result.py", line 33, in from_call
    result = func()
  File "/tmp/pa-test2/venv/lib/python3.9/site-packages/pluggy/_manager.py", line 324, in &lt;lambda&gt;
    lambda: oldcall(hook_name, hook_impls, kwargs, firstresult)
  File "/tmp/pa-test2/venv/lib/python3.9/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/tmp/pa-test2/venv/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/tmp/pa-test2/venv/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/tmp/pa-test2/venv/lib/python3.9/site-packages/_pytest/main.py", line 332, in pytest_collection
    session.perform_collect()
  File "/tmp/pa-test2/venv/lib/python3.9/site-packages/_pytest/main.py", line 657, in perform_collect
    self.items.extend(self.genitems(node))
  File "/tmp/pa-test2/venv/lib/python3.9/site-packages/_pytest/main.py", line 824, in genitems
    rep = collect_one_node(node)
  File "/tmp/pa-test2/venv/lib/python3.9/site-packages/_pytest/runner.py", line 537, in collect_one_node
    rep: CollectReport = ihook.pytest_make_collect_report(collector=collector)
  File "/tmp/pa-test2/venv/lib/python3.9/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/tmp/pa-test2/venv/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/tmp/pa-test2/venv/lib/python3.9/site-packages/pluggy/_manager.py", line 327, in traced_hookexec
    return outcome.get_result()
  File "/tmp/pa-test2/venv/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/tmp/pa-test2/venv/lib/python3.9/site-packages/pluggy/_result.py", line 33, in from_call
    result = func()
  File "/tmp/pa-test2/venv/lib/python3.9/site-packages/pluggy/_manager.py", line 324, in &lt;lambda&gt;
    lambda: oldcall(hook_name, hook_impls, kwargs, firstresult)
  File "/tmp/pa-test2/venv/lib/python3.9/site-packages/pluggy/_callers.py", line 55, in _multicall
    gen.send(outcome)
  File "/tmp/pa-test2/venv/lib/python3.9/site-packages/_pytest/capture.py", line 770, in pytest_make_collect_report
    rep = outcome.get_result()
  File "/tmp/pa-test2/venv/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/tmp/pa-test2/venv/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/tmp/pa-test2/venv/lib/python3.9/site-packages/_pytest/runner.py", line 388, in pytest_make_collect_report
    errorinfo = collector.repr_failure(call.excinfo)
  File "/tmp/pa-test2/venv/lib/python3.9/site-packages/_pytest/nodes.py", line 549, in repr_failure
    return self._repr_failure_py(excinfo, style=tbstyle)
  File "/tmp/pa-test2/venv/lib/python3.9/site-packages/_pytest/nodes.py", line 475, in _repr_failure_py
    return excinfo.getrepr(
  File "/tmp/pa-test2/venv/lib/python3.9/site-packages/_pytest/_code/code.py", line 666, in getrepr
    return fmt.repr_excinfo(self)
  File "/tmp/pa-test2/venv/lib/python3.9/site-packages/_pytest/_code/code.py", line 926, in repr_excinfo
    reprtraceback = self.repr_traceback(excinfo_)
  File "/tmp/pa-test2/venv/lib/python3.9/site-packages/_pytest/_code/code.py", line 867, in repr_traceback
    reprentry = self.repr_traceback_entry(entry, einfo)
  File "/tmp/pa-test2/venv/lib/python3.9/site-packages/_pytest/_code/code.py", line 818, in repr_traceback_entry
    s = self.get_source(source, line_index, excinfo, short=short)
  File "/tmp/pa-test2/venv/lib/python3.9/site-packages/_pytest/_code/code.py", line 747, in get_source
    lines.append(space_prefix + source.lines[line_index].strip())
IndexError: list index out of range</error>
    </testcase>
  </testsuite>
</testsuites>
```
It looks like an internal pytest error to me.

Looking at the junit-xml of the pytest-asyncio test suite, I cannot spot any empty test cases either. Could you provide some additional information on the problem you experience? An example junit-xml would be helpful I think. Ideally, it comes with a reproducible example.

**Comment by mh7d** [comment]
I tried to reproduce the bug, but I was not able to do so. 

Perhaps I had another plugin enabled or used an olde version of pytest, which creates the bug. When reproducing, I found out, that my example has an error in the testcase, so I corrected it above. 

Now it generates a file looking like (which is just fine):

<?xml version="1.0" encoding="utf-8"?>
<testsuites>
    <testsuite name="pytest" errors="0" failures="0" skipped="0" tests="1" time="0.038"
               timestamp="xxxx" hostname="xxxx">
        <testcase classname="test_junitxml_using_one_async_testcase" name="test_run" time="0.003"/>
    </testsuite>
</testsuites>

In my old test results it looked like:

<?xml version="1.0" encoding="utf-8"?>
<testsuites>
    <testsuite name="pytest" errors="0" failures="0" skipped="0" tests="1" time="0.031"
               timestamp="xxxx" hostname="xxxxx">
        <testcase time="0.001"/>
        <testcase classname="test_junitxml_using_one_async_testcase" name="test_run" time="0.002"/>
    </testsuite>
</testsuites>

I hope you can nevertheless use the test case in your suite. I will close this report so far, as it is non reproducable at the moment.

**Comment by seifertm** [comment]
Thank you for the quick turnaround @mh7d!
