### ISSUE TITLE
Event loop closed too early, when use async sqlalchemy.

### ISSUE THREAD

**Issue by post-human-world** [pytest-dev/pytest-asyncio#491]
When i try to convert fastapi example into asynchronous orm, i got this error. But it is very strange that everything go fine when executing raw sql.

I already read
-  [Unexpected attached to a different loop errors #402](#402).

*conftest.py*

```py
import pytest
import asyncio
from typing import Generator

from sqlalchemy.ext.asyncio import create_async_engine, AsyncEngine, async_sessionmaker
from sqlalchemy.pool import NullPool


engine: AsyncEngine = create_async_engine(
    "postgresql+asyncpg://python:changethis@localhost:5432/fastapi", pool_pre_ping=True, poolclass=NullPool)

SessionLocal = async_sessionmaker(autoflush=True, bind=engine)


@pytest.fixture(scope='session')
def event_loop():
    yield asyncio.get_event_loop()


@pytest.fixture(scope="session")
def db() -> Generator:
    yield SessionLocal()
```

*test_sql.py*

```py
from typing import Any

import pytest
from sqlalchemy import Boolean, Column, Integer, String, select
from sqlalchemy.orm import as_declarative
from sqlalchemy.ext.asyncio import AsyncSession as Session
from sqlalchemy.ext.declarative import declared_attr


@as_declarative()
class Base:
    id: Any
    __name__: str

    @declared_attr
    def __tablename__(cls) -> str:
        return cls.__name__.lower()


class User(Base):
    id = Column(Integer, primary_key=True, index=True)
    full_name = Column(String, index=True)
    email = Column(String, unique=True, index=True, nullable=False)
    hashed_password = Column(String, nullable=False)
    is_active = Column(Boolean(), default=True)
    is_superuser = Column(Boolean(), default=False)


@pytest.mark.asyncio
async def test_query1(db: Session):
    result = await db.run_sync(lambda db: db.query(User).filter(User.id == 1).first())
    assert result.id is not None


@pytest.mark.asyncio
async def test_query2(db: Session):
    statm = select(User).where(User.id == 1)
    result = await db.execute(statm)
    user = result.first()[0]
    assert user.id == 1
```

*Error*
```
===================================================== test session starts =====================================================
platform win32 -- Python 3.9.16, pytest-7.2.1, pluggy-1.0.0
rootdir: F:\...\sample-sqlalchemy\pytest-async, configfile: pyproject.toml, testpaths: tests
plugins: asyncio-0.20.3, cov-2.12.1
asyncio: mode=strict
collected 2 items

tests\test_sql.py ..                                                                                                     [100%]

=========================================================== PASSES ============================================================
=================================================== short test summary info ===================================================
PASSED tests/test_sql.py::test_query1
PASSED tests/test_sql.py::test_query2
====================================================== 2 passed in 0.23s ======================================================
Exception during reset or similar
Traceback (most recent call last):
  File "C...\pypoetry\Cache\virtualenvs\app-xUcRcb5R-py3.9\lib\site-packages\sqlalchemy\pool\base.py", line 983, in _finalize_fairy
    fairy._reset(
  File "C...\pypoetry\Cache\virtualenvs\app-xUcRcb5R-py3.9\lib\site-packages\sqlalchemy\pool\base.py", line 1422, in _reset
    pool._dialect.do_rollback(self)
  File "C...\pypoetry\Cache\virtualenvs\app-xUcRcb5R-py3.9\lib\site-packages\sqlalchemy\engine\default.py", line 657, in do_rollback
    dbapi_connection.rollback()
  File "C...\pypoetry\Cache\virtualenvs\app-xUcRcb5R-py3.9\lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 772, in rollback
    self._handle_exception(error)
  File "C...\pypoetry\Cache\virtualenvs\app-xUcRcb5R-py3.9\lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 719, in _handle_exception
    raise error
  File "C...\pypoetry\Cache\virtualenvs\app-xUcRcb5R-py3.9\lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 770, in rollback
    self.await_(self._transaction.rollback())
  File "C...\pypoetry\Cache\virtualenvs\app-xUcRcb5R-py3.9\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 93, in await_only
    raise exc.MissingGreenlet(
sqlalchemy.exc.MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)
Exception closing connection <AdaptedConnection <asyncpg.connection.Connection object at 0x000001851147E2E0>>
Traceback (most recent call last):
  File "C...\pypoetry\Cache\virtualenvs\app-xUcRcb5R-py3.9\lib\site-packages\sqlalchemy\pool\base.py", line 983, in _finalize_fairy
    fairy._reset(
  File "C...\pypoetry\Cache\virtualenvs\app-xUcRcb5R-py3.9\lib\site-packages\sqlalchemy\pool\base.py", line 1422, in _reset
    pool._dialect.do_rollback(self)
  File "C...\pypoetry\Cache\virtualenvs\app-xUcRcb5R-py3.9\lib\site-packages\sqlalchemy\engine\default.py", line 657, in do_rollback
    dbapi_connection.rollback()
  File "C...\pypoetry\Cache\virtualenvs\app-xUcRcb5R-py3.9\lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 772, in rollback
    self._handle_exception(error)
  File "C...\pypoetry\Cache\virtualenvs\app-xUcRcb5R-py3.9\lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 719, in _handle_exception
    raise error
  File "C...\pypoetry\Cache\virtualenvs\app-xUcRcb5R-py3.9\lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 770, in rollback
    self.await_(self._transaction.rollback())
  File "C...\pypoetry\Cache\virtualenvs\app-xUcRcb5R-py3.9\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 93, in await_only
    raise exc.MissingGreenlet(
sqlalchemy.exc.MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C...\pypoetry\Cache\virtualenvs\app-xUcRcb5R-py3.9\lib\site-packages\sqlalchemy\pool\base.py", line 380, in _close_connection
    self._dialect.do_terminate(connection)
  File "C...\pypoetry\Cache\virtualenvs\app-xUcRcb5R-py3.9\lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 984, in do_terminate
    dbapi_connection.terminate()
  File "C...\pypoetry\Cache\virtualenvs\app-xUcRcb5R-py3.9\lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 793, in terminate
    self._connection.terminate()
  File "C...\pypoetry\Cache\virtualenvs\app-xUcRcb5R-py3.9\lib\site-packages\asyncpg\connection.py", line 1344, in terminate
    self._abort()
  File "C...\pypoetry\Cache\virtualenvs\app-xUcRcb5R-py3.9\lib\site-packages\asyncpg\connection.py", line 1371, in _abort
    self._protocol.abort()
  File "asyncpg\protocol\protocol.pyx", line 570, in asyncpg.protocol.protocol.BaseProtocol.abort
  File "asyncpg\protocol\coreproto.pyx", line 1109, in asyncpg.protocol.protocol.CoreProtocol._terminate
  File "asyncpg\protocol\protocol.pyx", line 929, in asyncpg.protocol.protocol.BaseProtocol._write
  File "H:\anaconda\lib\asyncio\proactor_events.py", line 359, in write
    self._loop_writing(data=bytes(data))
  File "H:\anaconda\lib\asyncio\proactor_events.py", line 395, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'
sys:1: RuntimeWarning: coroutine 'Transaction.rollback' was never awaited
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001850F9ADF70>
Traceback (most recent call last):
  File "H:\anaconda\lib\asyncio\proactor_events.py", line 116, in __del__
  File "H:\anaconda\lib\asyncio\proactor_events.py", line 108, in close
  File "H:\anaconda\lib\asyncio\base_events.py", line 751, in call_soon
  File "H:\anaconda\lib\asyncio\base_events.py", line 515, in _check_closed
RuntimeError: Event loop is closed
```

*dependencies*

- python = "^3.9"
- psycopg2-binary = "^2.9.3"
- asyncpg = "0.27.0"
- alembic = "^1.9.2"
- sqlalchemy = {extras = ["asyncio"], version = "^2.0.0"}
- pytest = { version = "^7.2.0" }
- pytest-asyncio = "0.20.3"

**Comment by seifertm** [comment]
I suspect a problem with the order in which the fixtures are torn down. Could you run your tests with pytest's `--setup-show` option and post the output?

**Comment by post-human-world** [comment]
This is what i got with `pytest --setup-show`. The order of fixtures look good.

```
plugins: asyncio-0.20.3
asyncio: mode=strict
collected 2 items

tests\test_sql.py
SETUP    S event_loop
SETUP    S db
        tests/test_sql.py::test_query1 (fixtures used: db, event_loop).
        tests/test_sql.py::test_query2 (fixtures used: db, event_loop).
TEARDOWN S db
TEARDOWN S event_loop

=================================== PASSES ====================================
=========================== short test summary info ===========================
PASSED tests/test_sql.py::test_query1
PASSED tests/test_sql.py::test_query2
============================== 2 passed in 0.23s ==============================
Exception during reset or similar
Traceback (most recent call last):
...
```

**Comment by post-human-world** [comment]
Ok, i found how to solve this problem.

```py
@pytest.fixture(scope="session")
def db() -> Generator:
    try:
        db = SessionLocal()
        yield db
    finally:
        db.close()
```

**Comment by post-human-world** [comment]
It needs to close database before teardown action.

```py
@pytest.fixture(scope="session")
def db(event_loop) -> Generator:
    try:
        db = SessionLocal()
        yield db
    finally:
        event_loop.run_until_complete(db.close())
 ```
