### ISSUE TITLE
Startup failure on Windows with Version 0.23.0

### ISSUE THREAD

**Issue by blink1073** [pytest-dev/pytest-asyncio#701]
Hi!  We started noticing this failure on our windows builds with the new `0.23.0` release:

https://github.com/ipython/ipykernel/actions/runs/7078187154/job/19263404026?pr=1177

```
 ============================= test session starts =============================
platform win32 -- Python 3.8.10, pytest-7.4.3, pluggy-1.3.0 -- C:\Users\runneradmin\AppData\Local\hatch\env\virtual\ipykernel\nS5Qyasy\test\Scripts\python.exe
cachedir: .pytest_cache
rootdir: D:\a\ipykernel\ipykernel
configfile: pyproject.toml
testpaths: tests, tests/inprocess
plugins: flaky-3.7.0, asyncio-0.23.0, cov-4.1.0, timeout-2.2.0
asyncio: mode=auto
timeout: 300.0s
timeout method: thread
timeout func_only: False
collecting ... collected 21 items
run-last-failure: None
INTERNALERROR> Traceback (most recent call last):
...
INTERNALERROR>   File "C:\Users\runneradmin\AppData\Local\hatch\env\virtual\ipykernel\nS5Qyasy\test\lib\site-packages\pytest_asyncio\plugin.py", line 610, in pytest_collectstart
...
INTERNALERROR>   File "C:\Users\runneradmin\AppData\Local\hatch\env\virtual\ipykernel\nS5Qyasy\test\lib\site-packages\_pytest\outcomes.py", line 179, in skip
INTERNALERROR>     raise Skipped(msg=reason, allow_module_level=allow_module_level)
INTERNALERROR> Skipped: skipping tests on windows

============================= 1 warning in 0.05s ==============================
```

**Comment by seifertm** [comment]
@blink1073 pytest-asyncio v0.23.1 was just released and it should resolve the issue.

**Comment by blink1073** [comment]
Confirmed, thank you!
